TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 2.2
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.35
  
  sim_time: 3.0

  holonomic_robot: false
  heading_scoring: true
