obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.17
inflation_radius: 0.35
map_type: costmap
observation_sources: sick300

sick300: {data_type: LaserScan, topic: laserscan, marking: true, clearing: true}
